name: build-and-deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build both Vite apps and deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build cmsInterface
        working-directory: cmsInterface
        run: |
          npm ci
          npm run build

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Configure AWS Credentials for CMS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID_CM }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET_CM }}
          aws-region: ${{ vars.REGION }}

      - name: Sync CMS interface to S3
        run: |
          set -euo pipefail
          echo "Listing cmsInterface/dist contents"
          ls -la cmsInterface/dist || true
          # CMS Vite builds with base '/admin/' so asset URLs resolve under /admin; sync to /admin prefix
          if [ -d "cmsInterface/dist" ]; then
            # Mirror exactly under /admin
            aws s3 sync cmsInterface/dist s3://${{ vars.CODECM_BUCKET }}/admin --delete
            # Also copy to bucket root (no delete) if you want root to serve the same app
            aws s3 sync cmsInterface/dist s3://${{ vars.CODECM_BUCKET }}
            # Ensure index.html exists at /admin/index.html
            if [ -f "cmsInterface/dist/index.html" ]; then
              aws s3 cp cmsInterface/dist/index.html s3://${{ vars.CODECM_BUCKET }}/admin/index.html
            fi
          else
            echo "No cmsInterface/dist folder found, skipping CMS sync."
          fi

          

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID_FE }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET_FE }}
          aws-region: ${{ vars.REGION }}

      - name: Sync frontend to S3
        run: |
          set -xe
          echo "Listing frontend/dist contents"
          ls -la ./frontend/dist || true
          echo "Running aws s3 sync"
          aws s3 sync ./frontend/dist s3://${{ vars.FRONTEND_BUCKET }} --delete || {
            echo "aws s3 sync failed with exit code $? - retrying with --debug to capture details"
            aws s3 sync ./frontend/dist s3://${{ vars.FRONTEND_BUCKET }} --delete --debug
            exit 1
          }
      
